//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: download.proto
namespace wireless_android_skyjam
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTracksToExportRequest")]
  public partial class GetTracksToExportRequest : global::ProtoBuf.IExtensible
  {
    public GetTracksToExportRequest() {}
    
    private string _client_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"client_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string client_id
    {
      get { return _client_id; }
      set { _client_id = value; }
    }
    private string _continuation_token = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"continuation_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string continuation_token
    {
      get { return _continuation_token; }
      set { _continuation_token = value; }
    }
    private wireless_android_skyjam.GetTracksToExportRequest.TracksToExportType _export_type = wireless_android_skyjam.GetTracksToExportRequest.TracksToExportType.ALL;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"export_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.GetTracksToExportRequest.TracksToExportType.ALL)]
    public wireless_android_skyjam.GetTracksToExportRequest.TracksToExportType export_type
    {
      get { return _export_type; }
      set { _export_type = value; }
    }
    private long _updated_min = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"updated_min", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long updated_min
    {
      get { return _updated_min; }
      set { _updated_min = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"TracksToExportType")]
    public enum TracksToExportType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALL", Value=1)]
      ALL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PURCHASED_AND_PROMOTIONAL", Value=2)]
      PURCHASED_AND_PROMOTIONAL = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DownloadTrackInfo")]
  public partial class DownloadTrackInfo : global::ProtoBuf.IExtensible
  {
    public DownloadTrackInfo() {}
    
    private string _id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _album = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"album", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string album
    {
      get { return _album; }
      set { _album = value; }
    }
    private string _album_artist = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"album_artist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string album_artist
    {
      get { return _album_artist; }
      set { _album_artist = value; }
    }
    private string _artist = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"artist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string artist
    {
      get { return _artist; }
      set { _artist = value; }
    }
    private int _track_number = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"track_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int track_number
    {
      get { return _track_number; }
      set { _track_number = value; }
    }
    private long _track_size = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"track_size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long track_size
    {
      get { return _track_size; }
      set { _track_size = value; }
    }
    private int _disc_number = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"disc_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int disc_number
    {
      get { return _disc_number; }
      set { _disc_number = value; }
    }
    private int _total_disc_count = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"total_disc_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int total_disc_count
    {
      get { return _total_disc_count; }
      set { _total_disc_count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTracksToExportResponse")]
  public partial class GetTracksToExportResponse : global::ProtoBuf.IExtensible
  {
    public GetTracksToExportResponse() {}
    
    private wireless_android_skyjam.GetTracksToExportResponse.TracksToExportStatus _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public wireless_android_skyjam.GetTracksToExportResponse.TracksToExportStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.DownloadTrackInfo> _download_track_info = new global::System.Collections.Generic.List<wireless_android_skyjam.DownloadTrackInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"download_track_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.DownloadTrackInfo> download_track_info
    {
      get { return _download_track_info; }
    }
  
    private string _continuation_token = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"continuation_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string continuation_token
    {
      get { return _continuation_token; }
      set { _continuation_token = value; }
    }
    private long _updated_min = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"updated_min", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long updated_min
    {
      get { return _updated_min; }
      set { _updated_min = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"TracksToExportStatus")]
    public enum TracksToExportStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OK", Value=1)]
      OK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRANSIENT_ERROR", Value=2)]
      TRANSIENT_ERROR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_NUM_CLIENTS_REACHED", Value=3)]
      MAX_NUM_CLIENTS_REACHED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNABLE_TO_AUTHENTICATE_CLIENT", Value=4)]
      UNABLE_TO_AUTHENTICATE_CLIENT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNABLE_TO_REGISTER_CLIENT", Value=5)]
      UNABLE_TO_REGISTER_CLIENT = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}