//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: locker.proto
// Note: requires additional types generated from: uits.proto
namespace wireless_android_skyjam
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AudioRef")]
  public partial class AudioRef : global::ProtoBuf.IExtensible
  {
    public AudioRef() {}
    
    private wireless_android_skyjam.AudioRef.Store _store;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"store", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public wireless_android_skyjam.AudioRef.Store store
    {
      get { return _store; }
      set { _store = value; }
    }
    private byte[] _ref;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ref", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] @ref
    {
      get { return _ref; }
      set { _ref = value; }
    }
    private string _url = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string url
    {
      get { return _url; }
      set { _url = value; }
    }
    private int _bit_rate = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"bit_rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bit_rate
    {
      get { return _bit_rate; }
      set { _bit_rate = value; }
    }
    private int _sample_rate = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sample_rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sample_rate
    {
      get { return _sample_rate; }
      set { _sample_rate = value; }
    }
    private bool _downloadable = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"downloadable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool downloadable
    {
      get { return _downloadable; }
      set { _downloadable = value; }
    }
    private long _duration_millis = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"duration_millis", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long duration_millis
    {
      get { return _duration_millis; }
      set { _duration_millis = value; }
    }
    private long _rematch_timestamp = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"rematch_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long rematch_timestamp
    {
      get { return _rematch_timestamp; }
      set { _rematch_timestamp = value; }
    }
    private bool _invalid_due_to_wipeout = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"invalid_due_to_wipeout", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool invalid_due_to_wipeout
    {
      get { return _invalid_due_to_wipeout; }
      set { _invalid_due_to_wipeout = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Store")]
    public enum Store
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLOBSTORE", Value=1)]
      BLOBSTORE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SM_V2", Value=2)]
      SM_V2 = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ImageRef")]
  public partial class ImageRef : global::ProtoBuf.IExtensible
  {
    public ImageRef() {}
    
    private wireless_android_skyjam.ImageRef.Store _store = wireless_android_skyjam.ImageRef.Store.SHOEBOX;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"store", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.ImageRef.Store.SHOEBOX)]
    public wireless_android_skyjam.ImageRef.Store store
    {
      get { return _store; }
      set { _store = value; }
    }
    private uint _width = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint width
    {
      get { return _width; }
      set { _width = value; }
    }
    private uint _height = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint height
    {
      get { return _height; }
      set { _height = value; }
    }
    private string _url = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string url
    {
      get { return _url; }
      set { _url = value; }
    }
    private bool _invalid_due_to_wipeout = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"invalid_due_to_wipeout", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool invalid_due_to_wipeout
    {
      get { return _invalid_due_to_wipeout; }
      set { _invalid_due_to_wipeout = value; }
    }
    private wireless_android_skyjam.ImageRef.Origin _origin = wireless_android_skyjam.ImageRef.Origin.PERSONAL;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"origin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.ImageRef.Origin.PERSONAL)]
    public wireless_android_skyjam.ImageRef.Origin origin
    {
      get { return _origin; }
      set { _origin = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Store")]
    public enum Store
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOEBOX", Value=3)]
      SHOEBOX = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Origin")]
    public enum Origin
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PERSONAL", Value=1)]
      PERSONAL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STORE", Value=2)]
      STORE = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UploadedUitsId3Tag")]
  public partial class UploadedUitsId3Tag : global::ProtoBuf.IExtensible
  {
    public UploadedUitsId3Tag() {}
    
    private string _owner = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"owner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string owner
    {
      get { return _owner; }
      set { _owner = value; }
    }
    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AdditionalMetadata")]
  public partial class AdditionalMetadata : global::ProtoBuf.IExtensible
  {
    public AdditionalMetadata() {}
    
    private string _tag_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tag_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tag_name
    {
      get { return _tag_name; }
      set { _tag_name = value; }
    }
    private byte[] _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TrackExtras")]
  public partial class TrackExtras : global::ProtoBuf.IExtensible
  {
    public TrackExtras() {}
    
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.AdditionalMetadata> _additional_metadata = new global::System.Collections.Generic.List<wireless_android_skyjam.AdditionalMetadata>();
    [global::ProtoBuf.ProtoMember(2, Name=@"additional_metadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.AdditionalMetadata> additional_metadata
    {
      get { return _additional_metadata; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Track")]
  public partial class Track : global::ProtoBuf.IExtensible
  {
    public Track() {}
    
    private string _id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _client_id = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"client_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string client_id
    {
      get { return _client_id; }
      set { _client_id = value; }
    }
    private long _creation_timestamp = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"creation_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long creation_timestamp
    {
      get { return _creation_timestamp; }
      set { _creation_timestamp = value; }
    }
    private long _last_modified_timestamp = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"last_modified_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long last_modified_timestamp
    {
      get { return _last_modified_timestamp; }
      set { _last_modified_timestamp = value; }
    }
    private bool _deleted = (bool)false;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"deleted", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool deleted
    {
      get { return _deleted; }
      set { _deleted = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _artist = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"artist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string artist
    {
      get { return _artist; }
      set { _artist = value; }
    }
    private long _artist_hash = default(long);
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"artist_hash", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long artist_hash
    {
      get { return _artist_hash; }
      set { _artist_hash = value; }
    }
    private string _composer = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"composer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string composer
    {
      get { return _composer; }
      set { _composer = value; }
    }
    private string _album = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"album", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string album
    {
      get { return _album; }
      set { _album = value; }
    }
    private string _album_artist = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"album_artist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string album_artist
    {
      get { return _album_artist; }
      set { _album_artist = value; }
    }
    private string _canonical_album = "";
    [global::ProtoBuf.ProtoMember(56, IsRequired = false, Name=@"canonical_album", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string canonical_album
    {
      get { return _canonical_album; }
      set { _canonical_album = value; }
    }
    private string _canonical_artist = "";
    [global::ProtoBuf.ProtoMember(57, IsRequired = false, Name=@"canonical_artist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string canonical_artist
    {
      get { return _canonical_artist; }
      set { _canonical_artist = value; }
    }
    private string _canonical_genre_album = "";
    [global::ProtoBuf.ProtoMember(58, IsRequired = false, Name=@"canonical_genre_album", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string canonical_genre_album
    {
      get { return _canonical_genre_album; }
      set { _canonical_genre_album = value; }
    }
    private int _year = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"year", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int year
    {
      get { return _year; }
      set { _year = value; }
    }
    private string _comment = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"comment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string comment
    {
      get { return _comment; }
      set { _comment = value; }
    }
    private int _track_number = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"track_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int track_number
    {
      get { return _track_number; }
      set { _track_number = value; }
    }
    private string _genre = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"genre", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string genre
    {
      get { return _genre; }
      set { _genre = value; }
    }
    private long _duration_millis = default(long);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"duration_millis", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long duration_millis
    {
      get { return _duration_millis; }
      set { _duration_millis = value; }
    }
    private int _beats_per_minute = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"beats_per_minute", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int beats_per_minute
    {
      get { return _beats_per_minute; }
      set { _beats_per_minute = value; }
    }
    private int _original_bit_rate = default(int);
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"original_bit_rate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int original_bit_rate
    {
      get { return _original_bit_rate; }
      set { _original_bit_rate = value; }
    }
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.AudioRef> _audio_ref = new global::System.Collections.Generic.List<wireless_android_skyjam.AudioRef>();
    [global::ProtoBuf.ProtoMember(17, Name=@"audio_ref", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.AudioRef> audio_ref
    {
      get { return _audio_ref; }
    }
  
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.ImageRef> _album_art_ref = new global::System.Collections.Generic.List<wireless_android_skyjam.ImageRef>();
    [global::ProtoBuf.ProtoMember(18, Name=@"album_art_ref", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.ImageRef> album_art_ref
    {
      get { return _album_art_ref; }
    }
  
    private wireless_android_skyjam.Track.AvailabilityStatus _availability_status = wireless_android_skyjam.Track.AvailabilityStatus.PENDING;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"availability_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.Track.AvailabilityStatus.PENDING)]
    public wireless_android_skyjam.Track.AvailabilityStatus availability_status
    {
      get { return _availability_status; }
      set { _availability_status = value; }
    }
    private int _play_count = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"play_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int play_count
    {
      get { return _play_count; }
      set { _play_count = value; }
    }
    private wireless_android_skyjam.Track.ContentType _content_type = wireless_android_skyjam.Track.ContentType.MP3;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"content_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.Track.ContentType.MP3)]
    public wireless_android_skyjam.Track.ContentType content_type
    {
      get { return _content_type; }
      set { _content_type = value; }
    }
    private int _total_track_count = default(int);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"total_track_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int total_track_count
    {
      get { return _total_track_count; }
      set { _total_track_count = value; }
    }
    private int _disc_number = default(int);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"disc_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int disc_number
    {
      get { return _disc_number; }
      set { _disc_number = value; }
    }
    private int _total_disc_count = default(int);
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"total_disc_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int total_disc_count
    {
      get { return _total_disc_count; }
      set { _total_disc_count = value; }
    }
    private wireless_android_skyjam.Track.Channels _channels = wireless_android_skyjam.Track.Channels.MONO;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"channels", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.Track.Channels.MONO)]
    public wireless_android_skyjam.Track.Channels channels
    {
      get { return _channels; }
      set { _channels = value; }
    }
    private wireless_android_skyjam.Track.TrackType _track_type = wireless_android_skyjam.Track.TrackType.MATCHED_TRACK;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"track_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.Track.TrackType.MATCHED_TRACK)]
    public wireless_android_skyjam.Track.TrackType track_type
    {
      get { return _track_type; }
      set { _track_type = value; }
    }
    private bool _use_single_server_copy = default(bool);
    [global::ProtoBuf.ProtoMember(59, IsRequired = false, Name=@"use_single_server_copy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool use_single_server_copy
    {
      get { return _use_single_server_copy; }
      set { _use_single_server_copy = value; }
    }
    private wireless_android_skyjam.Track.Rating _rating = wireless_android_skyjam.Track.Rating.NOT_RATED;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"rating", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.Track.Rating.NOT_RATED)]
    public wireless_android_skyjam.Track.Rating rating
    {
      get { return _rating; }
      set { _rating = value; }
    }
    private long _estimated_size = default(long);
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"estimated_size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long estimated_size
    {
      get { return _estimated_size; }
      set { _estimated_size = value; }
    }
    private string _store_id = "";
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"store_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string store_id
    {
      get { return _store_id; }
      set { _store_id = value; }
    }
    private string _metajam_id = "";
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"metajam_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string metajam_id
    {
      get { return _metajam_id; }
      set { _metajam_id = value; }
    }
    private double _metajam_id_confidence = (double)0;
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"metajam_id_confidence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((double)0)]
    public double metajam_id_confidence
    {
      get { return _metajam_id_confidence; }
      set { _metajam_id_confidence = value; }
    }
    private string _uits = "";
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"uits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uits
    {
      get { return _uits; }
      set { _uits = value; }
    }
    private wireless_android_skyjam.UitsMetadata _uits_metadata = null;
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"uits_metadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public wireless_android_skyjam.UitsMetadata uits_metadata
    {
      get { return _uits_metadata; }
      set { _uits_metadata = value; }
    }
    private bool _compilation = default(bool);
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"compilation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool compilation
    {
      get { return _compilation; }
      set { _compilation = value; }
    }
    private long _client_date_added = default(long);
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"client_date_added", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long client_date_added
    {
      get { return _client_date_added; }
      set { _client_date_added = value; }
    }
    private long _recent_timestamp = default(long);
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"recent_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long recent_timestamp
    {
      get { return _recent_timestamp; }
      set { _recent_timestamp = value; }
    }
    private bool _do_not_rematch = (bool)false;
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"do_not_rematch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool do_not_rematch
    {
      get { return _do_not_rematch; }
      set { _do_not_rematch = value; }
    }
    private bool _from_album_purchase = default(bool);
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"from_album_purchase", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool from_album_purchase
    {
      get { return _from_album_purchase; }
      set { _from_album_purchase = value; }
    }
    private string _album_metajam_id = "";
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"album_metajam_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string album_metajam_id
    {
      get { return _album_metajam_id; }
      set { _album_metajam_id = value; }
    }
    private string _transaction_id = "";
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"transaction_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string transaction_id
    {
      get { return _transaction_id; }
      set { _transaction_id = value; }
    }
    private bool _debug_track = default(bool);
    [global::ProtoBuf.ProtoMember(47, IsRequired = false, Name=@"debug_track", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool debug_track
    {
      get { return _debug_track; }
      set { _debug_track = value; }
    }
    private string _normalized_title = "";
    [global::ProtoBuf.ProtoMember(48, IsRequired = false, Name=@"normalized_title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string normalized_title
    {
      get { return _normalized_title; }
      set { _normalized_title = value; }
    }
    private string _normalized_artist = "";
    [global::ProtoBuf.ProtoMember(49, IsRequired = false, Name=@"normalized_artist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string normalized_artist
    {
      get { return _normalized_artist; }
      set { _normalized_artist = value; }
    }
    private string _normalized_album = "";
    [global::ProtoBuf.ProtoMember(50, IsRequired = false, Name=@"normalized_album", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string normalized_album
    {
      get { return _normalized_album; }
      set { _normalized_album = value; }
    }
    private string _normalized_album_artist = "";
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"normalized_album_artist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string normalized_album_artist
    {
      get { return _normalized_album_artist; }
      set { _normalized_album_artist = value; }
    }
    private string _normalized_canonical_album = "";
    [global::ProtoBuf.ProtoMember(54, IsRequired = false, Name=@"normalized_canonical_album", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string normalized_canonical_album
    {
      get { return _normalized_canonical_album; }
      set { _normalized_canonical_album = value; }
    }
    private string _normalized_canonical_artist = "";
    [global::ProtoBuf.ProtoMember(55, IsRequired = false, Name=@"normalized_canonical_artist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string normalized_canonical_artist
    {
      get { return _normalized_canonical_artist; }
      set { _normalized_canonical_artist = value; }
    }
    private string _uploader_id = "";
    [global::ProtoBuf.ProtoMember(52, IsRequired = false, Name=@"uploader_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uploader_id
    {
      get { return _uploader_id; }
      set { _uploader_id = value; }
    }
    private string _client_album_id = "";
    [global::ProtoBuf.ProtoMember(53, IsRequired = false, Name=@"client_album_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string client_album_id
    {
      get { return _client_album_id; }
      set { _client_album_id = value; }
    }
    private string _label_owner_code = "";
    [global::ProtoBuf.ProtoMember(60, IsRequired = false, Name=@"label_owner_code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string label_owner_code
    {
      get { return _label_owner_code; }
      set { _label_owner_code = value; }
    }
    private wireless_android_skyjam.Track.ContentType _original_content_type = wireless_android_skyjam.Track.ContentType.MP3;
    [global::ProtoBuf.ProtoMember(61, IsRequired = false, Name=@"original_content_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.Track.ContentType.MP3)]
    public wireless_android_skyjam.Track.ContentType original_content_type
    {
      get { return _original_content_type; }
      set { _original_content_type = value; }
    }
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.UploadedUitsId3Tag> _uploaded_uits = new global::System.Collections.Generic.List<wireless_android_skyjam.UploadedUitsId3Tag>();
    [global::ProtoBuf.ProtoMember(71, Name=@"uploaded_uits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.UploadedUitsId3Tag> uploaded_uits
    {
      get { return _uploaded_uits; }
    }
  
    private wireless_android_skyjam.Track.ExplicitType _explicit_type = wireless_android_skyjam.Track.ExplicitType.EXPLICIT;
    [global::ProtoBuf.ProtoMember(74, IsRequired = false, Name=@"explicit_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.Track.ExplicitType.EXPLICIT)]
    public wireless_android_skyjam.Track.ExplicitType explicit_type
    {
      get { return _explicit_type; }
      set { _explicit_type = value; }
    }
    private wireless_android_skyjam.TrackExtras _track_extras = null;
    [global::ProtoBuf.ProtoMember(75, IsRequired = false, Name=@"track_extras", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public wireless_android_skyjam.TrackExtras track_extras
    {
      get { return _track_extras; }
      set { _track_extras = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"AvailabilityStatus")]
    public enum AvailabilityStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PENDING", Value=1)]
      PENDING = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MATCHED", Value=2)]
      MATCHED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPLOAD_REQUESTED", Value=3)]
      UPLOAD_REQUESTED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AVAILABLE", Value=4)]
      AVAILABLE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE_REUPLOAD", Value=5)]
      FORCE_REUPLOAD = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPLOAD_PERMANENTLY_FAILED", Value=6)]
      UPLOAD_PERMANENTLY_FAILED = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ContentType")]
    public enum ContentType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MP3", Value=1)]
      MP3 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"M4A", Value=2)]
      M4A = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AAC", Value=3)]
      AAC = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FLAC", Value=4)]
      FLAC = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OGG", Value=5)]
      OGG = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WMA", Value=6)]
      WMA = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"M4P", Value=7)]
      M4P = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALAC", Value=8)]
      ALAC = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Channels")]
    public enum Channels
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MONO", Value=1)]
      MONO = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STEREO", Value=2)]
      STEREO = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TrackType")]
    public enum TrackType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MATCHED_TRACK", Value=1)]
      MATCHED_TRACK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNMATCHED_TRACK", Value=2)]
      UNMATCHED_TRACK = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOCAL_TRACK", Value=3)]
      LOCAL_TRACK = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PURCHASED_TRACK", Value=4)]
      PURCHASED_TRACK = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"METADATA_ONLY_MATCHED_TRACK", Value=5)]
      METADATA_ONLY_MATCHED_TRACK = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROMO_TRACK", Value=6)]
      PROMO_TRACK = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Rating")]
    public enum Rating
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_RATED", Value=1)]
      NOT_RATED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ONE_STAR", Value=2)]
      ONE_STAR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TWO_STARS", Value=3)]
      TWO_STARS = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"THREE_STARS", Value=4)]
      THREE_STARS = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FOUR_STARS", Value=5)]
      FOUR_STARS = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIVE_STARS", Value=6)]
      FIVE_STARS = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ExplicitType")]
    public enum ExplicitType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXPLICIT", Value=1)]
      EXPLICIT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLEAN", Value=2)]
      CLEAN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EDITED", Value=3)]
      EDITED = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Tracks")]
  public partial class Tracks : global::ProtoBuf.IExtensible
  {
    public Tracks() {}
    
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.Track> _track = new global::System.Collections.Generic.List<wireless_android_skyjam.Track>();
    [global::ProtoBuf.ProtoMember(1, Name=@"track", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.Track> track
    {
      get { return _track; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Playlist")]
  public partial class Playlist : global::ProtoBuf.IExtensible
  {
    public Playlist() {}
    
    private string _id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _client_id = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"client_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string client_id
    {
      get { return _client_id; }
      set { _client_id = value; }
    }
    private long _creation_timestamp = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"creation_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long creation_timestamp
    {
      get { return _creation_timestamp; }
      set { _creation_timestamp = value; }
    }
    private long _last_modified_timestamp = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"last_modified_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long last_modified_timestamp
    {
      get { return _last_modified_timestamp; }
      set { _last_modified_timestamp = value; }
    }
    private bool _deleted = (bool)false;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"deleted", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool deleted
    {
      get { return _deleted; }
      set { _deleted = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private wireless_android_skyjam.Playlist.PlaylistType _playlist_type = wireless_android_skyjam.Playlist.PlaylistType.USER_GENERATED;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"playlist_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.Playlist.PlaylistType.USER_GENERATED)]
    public wireless_android_skyjam.Playlist.PlaylistType playlist_type
    {
      get { return _playlist_type; }
      set { _playlist_type = value; }
    }
    private wireless_android_skyjam.ImageRef _playlist_art_ref = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"playlist_art_ref", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public wireless_android_skyjam.ImageRef playlist_art_ref
    {
      get { return _playlist_art_ref; }
      set { _playlist_art_ref = value; }
    }
    private long _recent_timestamp = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"recent_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long recent_timestamp
    {
      get { return _recent_timestamp; }
      set { _recent_timestamp = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"PlaylistType")]
    public enum PlaylistType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_GENERATED", Value=1)]
      USER_GENERATED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAGIC", Value=2)]
      MAGIC = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PROMO", Value=3)]
      PROMO = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlaylistEntry")]
  public partial class PlaylistEntry : global::ProtoBuf.IExtensible
  {
    public PlaylistEntry() {}
    
    private string _playlist_id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playlist_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playlist_id
    {
      get { return _playlist_id; }
      set { _playlist_id = value; }
    }
    private long _absolute_position = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"absolute_position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long absolute_position
    {
      get { return _absolute_position; }
      set { _absolute_position = value; }
    }
    private string _place_after_entry_id = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"place_after_entry_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string place_after_entry_id
    {
      get { return _place_after_entry_id; }
      set { _place_after_entry_id = value; }
    }
    private string _track_id = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"track_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string track_id
    {
      get { return _track_id; }
      set { _track_id = value; }
    }
    private string _id = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _client_id = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"client_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string client_id
    {
      get { return _client_id; }
      set { _client_id = value; }
    }
    private long _creation_timestamp = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"creation_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long creation_timestamp
    {
      get { return _creation_timestamp; }
      set { _creation_timestamp = value; }
    }
    private long _last_modified_timestamp = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"last_modified_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long last_modified_timestamp
    {
      get { return _last_modified_timestamp; }
      set { _last_modified_timestamp = value; }
    }
    private bool _deleted = (bool)false;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"deleted", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool deleted
    {
      get { return _deleted; }
      set { _deleted = value; }
    }
    private wireless_android_skyjam.PlaylistEntry.RelativePositionIdType _relative_position_id_type = wireless_android_skyjam.PlaylistEntry.RelativePositionIdType.SERVER;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"relative_position_id_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.PlaylistEntry.RelativePositionIdType.SERVER)]
    public wireless_android_skyjam.PlaylistEntry.RelativePositionIdType relative_position_id_type
    {
      get { return _relative_position_id_type; }
      set { _relative_position_id_type = value; }
    }
    private wireless_android_skyjam.Track _track = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"track", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public wireless_android_skyjam.Track track
    {
      get { return _track; }
      set { _track = value; }
    }
    private string _place_before_entry_id = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"place_before_entry_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string place_before_entry_id
    {
      get { return _place_before_entry_id; }
      set { _place_before_entry_id = value; }
    }
    private string _string_position = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"string_position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string string_position
    {
      get { return _string_position; }
      set { _string_position = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"RelativePositionIdType")]
    public enum RelativePositionIdType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER", Value=1)]
      SERVER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT", Value=2)]
      CLIENT = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}