//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: uits.proto
namespace wireless_android_skyjam
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProductId")]
  public partial class ProductId : global::ProtoBuf.IExtensible
  {
    public ProductId() {}
    
    private wireless_android_skyjam.ProductId.Type _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public wireless_android_skyjam.ProductId.Type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private bool _completed = (bool)false;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"completed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool completed
    {
      get { return _completed; }
      set { _completed = value; }
    }
    private string _id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPC", Value=1)]
      UPC = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GRID", Value=2)]
      GRID = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AssetId")]
  public partial class AssetId : global::ProtoBuf.IExtensible
  {
    public AssetId() {}
    
    private wireless_android_skyjam.AssetId.Type _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public wireless_android_skyjam.AssetId.Type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ISRC", Value=1)]
      ISRC = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TransactionId")]
  public partial class TransactionId : global::ProtoBuf.IExtensible
  {
    public TransactionId() {}
    
    private string _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MediaId")]
  public partial class MediaId : global::ProtoBuf.IExtensible
  {
    public MediaId() {}
    
    private wireless_android_skyjam.MediaId.AlgorithmType _algorithm_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"algorithm_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public wireless_android_skyjam.MediaId.AlgorithmType algorithm_type
    {
      get { return _algorithm_type; }
      set { _algorithm_type = value; }
    }
    private string _hash;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hash", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string hash
    {
      get { return _hash; }
      set { _hash = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"AlgorithmType")]
    public enum AlgorithmType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHA256", Value=1)]
      SHA256 = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UrlInfo")]
  public partial class UrlInfo : global::ProtoBuf.IExtensible
  {
    public UrlInfo() {}
    
    private wireless_android_skyjam.UrlInfo.Type _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public wireless_android_skyjam.UrlInfo.Type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _url;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string url
    {
      get { return _url; }
      set { _url = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WCOM", Value=1)]
      WCOM = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WCOP", Value=2)]
      WCOP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WOAF", Value=3)]
      WOAF = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WOAR", Value=4)]
      WOAR = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WOAS", Value=5)]
      WOAS = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WORS", Value=6)]
      WORS = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WPAY", Value=7)]
      WPAY = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WPUB", Value=8)]
      WPUB = 8
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CopyrightStatus")]
  public partial class CopyrightStatus : global::ProtoBuf.IExtensible
  {
    public CopyrightStatus() {}
    
    private wireless_android_skyjam.CopyrightStatus.Type _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public wireless_android_skyjam.CopyrightStatus.Type type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _copyright = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"copyright", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string copyright
    {
      get { return _copyright; }
      set { _copyright = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNSPECIFIED", Value=1)]
      UNSPECIFIED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALLRIGHTSRESERVED", Value=2)]
      ALLRIGHTSRESERVED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PRERELEASE", Value=3)]
      PRERELEASE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER", Value=4)]
      OTHER = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Extra")]
  public partial class Extra : global::ProtoBuf.IExtensible
  {
    public Extra() {}
    
    private string _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UitsMetadata")]
  public partial class UitsMetadata : global::ProtoBuf.IExtensible
  {
    public UitsMetadata() {}
    
    private string _nonce;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"nonce", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nonce
    {
      get { return _nonce; }
      set { _nonce = value; }
    }
    private string _distributor_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"distributor_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string distributor_id
    {
      get { return _distributor_id; }
      set { _distributor_id = value; }
    }
    private string _transaction_date;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"transaction_date", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string transaction_date
    {
      get { return _transaction_date; }
      set { _transaction_date = value; }
    }
    private wireless_android_skyjam.ProductId _product_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"product_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public wireless_android_skyjam.ProductId product_id
    {
      get { return _product_id; }
      set { _product_id = value; }
    }
    private wireless_android_skyjam.AssetId _asset_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"asset_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public wireless_android_skyjam.AssetId asset_id
    {
      get { return _asset_id; }
      set { _asset_id = value; }
    }
    private wireless_android_skyjam.TransactionId _transaction_id;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"transaction_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public wireless_android_skyjam.TransactionId transaction_id
    {
      get { return _transaction_id; }
      set { _transaction_id = value; }
    }
    private wireless_android_skyjam.MediaId _media_id;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"media_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public wireless_android_skyjam.MediaId media_id
    {
      get { return _media_id; }
      set { _media_id = value; }
    }
    private wireless_android_skyjam.UrlInfo _url_info = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"url_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public wireless_android_skyjam.UrlInfo url_info
    {
      get { return _url_info; }
      set { _url_info = value; }
    }
    private wireless_android_skyjam.UitsMetadata.ParentalAdvisoryType _parental_advisory_type = wireless_android_skyjam.UitsMetadata.ParentalAdvisoryType.UNSPECIFIED;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"parental_advisory_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.UitsMetadata.ParentalAdvisoryType.UNSPECIFIED)]
    public wireless_android_skyjam.UitsMetadata.ParentalAdvisoryType parental_advisory_type
    {
      get { return _parental_advisory_type; }
      set { _parental_advisory_type = value; }
    }
    private wireless_android_skyjam.CopyrightStatus _copyright_status = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"copyright_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public wireless_android_skyjam.CopyrightStatus copyright_status
    {
      get { return _copyright_status; }
      set { _copyright_status = value; }
    }
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.Extra> _extra = new global::System.Collections.Generic.List<wireless_android_skyjam.Extra>();
    [global::ProtoBuf.ProtoMember(11, Name=@"extra", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.Extra> extra
    {
      get { return _extra; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ParentalAdvisoryType")]
    public enum ParentalAdvisoryType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNSPECIFIED", Value=1)]
      UNSPECIFIED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EXPLICIT", Value=2)]
      EXPLICIT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EDITED", Value=3)]
      EDITED = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UitsSignature")]
  public partial class UitsSignature : global::ProtoBuf.IExtensible
  {
    public UitsSignature() {}
    
    private wireless_android_skyjam.UitsSignature.AlgorithmType _algorithm_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"algorithm_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public wireless_android_skyjam.UitsSignature.AlgorithmType algorithm_type
    {
      get { return _algorithm_type; }
      set { _algorithm_type = value; }
    }
    private wireless_android_skyjam.UitsSignature.CanonicalizationType _canonicalization_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"canonicalization_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public wireless_android_skyjam.UitsSignature.CanonicalizationType canonicalization_type
    {
      get { return _canonicalization_type; }
      set { _canonicalization_type = value; }
    }
    private string _key_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"key_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key_id
    {
      get { return _key_id; }
      set { _key_id = value; }
    }
    private string _value;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"AlgorithmType")]
    public enum AlgorithmType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RSA2048", Value=1)]
      RSA2048 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DSA2048", Value=2)]
      DSA2048 = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CanonicalizationType")]
    public enum CanonicalizationType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NONE", Value=1)]
      NONE = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Uits")]
  public partial class Uits : global::ProtoBuf.IExtensible
  {
    public Uits() {}
    
    private wireless_android_skyjam.UitsMetadata _metadata;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"metadata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public wireless_android_skyjam.UitsMetadata metadata
    {
      get { return _metadata; }
      set { _metadata = value; }
    }
    private wireless_android_skyjam.UitsSignature _signature;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public wireless_android_skyjam.UitsSignature signature
    {
      get { return _signature; }
      set { _signature = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}