//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: upload.proto
// Note: requires additional types generated from: locker.proto
namespace wireless_android_skyjam
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResponseStatus")]
  public partial class ResponseStatus : global::ProtoBuf.IExtensible
  {
    public ResponseStatus() {}
    
    private wireless_android_skyjam.ResponseStatus.ResponseCode _response_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"response_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public wireless_android_skyjam.ResponseStatus.ResponseCode response_code
    {
      get { return _response_code; }
      set { _response_code = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ResponseCode")]
    public enum ResponseCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OK", Value=1)]
      OK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALREADY_EXISTS", Value=2)]
      ALREADY_EXISTS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SOFT_ERROR", Value=3)]
      SOFT_ERROR = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"METADATA_TOO_LARGE", Value=4)]
      METADATA_TOO_LARGE = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UploadOperation")]
  public partial class UploadOperation : global::ProtoBuf.IExtensible
  {
    public UploadOperation() {}
    
    private wireless_android_skyjam.UploadOperation.Operation _operation;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"operation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public wireless_android_skyjam.UploadOperation.Operation operation
    {
      get { return _operation; }
      set { _operation = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Operation")]
    public enum Operation
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPERATION_CREATE", Value=1)]
      OPERATION_CREATE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPERATION_MODIFY", Value=2)]
      OPERATION_MODIFY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OPERATION_DELETE", Value=3)]
      OPERATION_DELETE = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnhancedChallenge")]
  public partial class EnhancedChallenge : global::ProtoBuf.IExtensible
  {
    public EnhancedChallenge() {}
    
    private wireless_android_skyjam.EnhancedChallenge.HashAlgorithm _hash_algorithm = wireless_android_skyjam.EnhancedChallenge.HashAlgorithm.SHA_256;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hash_algorithm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.EnhancedChallenge.HashAlgorithm.SHA_256)]
    public wireless_android_skyjam.EnhancedChallenge.HashAlgorithm hash_algorithm
    {
      get { return _hash_algorithm; }
      set { _hash_algorithm = value; }
    }
    private byte[] _random_seed = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"random_seed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] random_seed
    {
      get { return _random_seed; }
      set { _random_seed = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"HashAlgorithm")]
    public enum HashAlgorithm
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHA_256", Value=1)]
      SHA_256 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MD5", Value=2)]
      MD5 = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChallengeInfo")]
  public partial class ChallengeInfo // : global::ProtoBuf.IExtensible
  {
    public ChallengeInfo() {}
    
    private string _client_track_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"client_track_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string client_track_id
    {
      get { return _client_track_id; }
      set { _client_track_id = value; }
    }
    private int _start_millis;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"start_millis", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public int start_millis
    {
      get { return _start_millis; }
      set { _start_millis = value; }
    }
    private int _duration_millis;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"duration_millis", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public int duration_millis
    {
      get { return _duration_millis; }
      set { _duration_millis = value; }
    }
    private string _challenge_user_id = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"challenge_user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string challenge_user_id
    {
      get { return _challenge_user_id; }
      set { _challenge_user_id = value; }
    }
    private long _challenge_timestamp = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"challenge_timestamp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long challenge_timestamp
    {
      get { return _challenge_timestamp; }
      set { _challenge_timestamp = value; }
    }
    private bool _expect_match = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"expect_match", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool expect_match
    {
      get { return _expect_match; }
      set { _expect_match = value; }
    }
    //private wireless_android_skyjam.EnhancedChallenge _enhanced_challenge = null;
    //[global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"enhanced_challenge", DataFormat = global::ProtoBuf.DataFormat.Default)]
    //[global::System.ComponentModel.DefaultValue(null)]
    //public wireless_android_skyjam.EnhancedChallenge enhanced_challenge
    //{
    //  get { return _enhanced_challenge; }
    //  set { _enhanced_challenge = value; }
    //}
    //private global::ProtoBuf.IExtension extensionObject;
    //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
    //  { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnhancedChallengeResponse")]
  public partial class EnhancedChallengeResponse : global::ProtoBuf.IExtensible
  {
    public EnhancedChallengeResponse() {}
    
    private byte[] _challenge_answer = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"challenge_answer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] challenge_answer
    {
      get { return _challenge_answer; }
      set { _challenge_answer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SignedChallengeInfo")]
  public partial class SignedChallengeInfo // : global::ProtoBuf.IExtensible
  {
    public SignedChallengeInfo() {}
    
    private wireless_android_skyjam.ChallengeInfo _challenge_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"challenge_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public wireless_android_skyjam.ChallengeInfo challenge_info
    {
      get { return _challenge_info; }
      set { _challenge_info = value; }
    }
    private byte[] _signature;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] signature
    {
      get { return _signature; }
      set { _signature = value; }
    }
    //private global::ProtoBuf.IExtension extensionObject;
    //global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
    //  { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TrackSample")]
  public partial class TrackSample : global::ProtoBuf.IExtensible
  {
    public TrackSample() {}
    
    private wireless_android_skyjam.Track _track;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"track", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public wireless_android_skyjam.Track track
    {
      get { return _track; }
      set { _track = value; }
    }
    private wireless_android_skyjam.SignedChallengeInfo _signed_challenge_info;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"signed_challenge_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public wireless_android_skyjam.SignedChallengeInfo signed_challenge_info
    {
      get { return _signed_challenge_info; }
      set { _signed_challenge_info = value; }
    }
    private byte[] _sample = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sample", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] sample
    {
      get { return _sample; }
      set { _sample = value; }
    }
    private wireless_android_skyjam.Track.ContentType _sample_format = wireless_android_skyjam.Track.ContentType.MP3;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sample_format", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.Track.ContentType.MP3)]
    public wireless_android_skyjam.Track.ContentType sample_format
    {
      get { return _sample_format; }
      set { _sample_format = value; }
    }
    private wireless_android_skyjam.ImageUnion _user_album_art = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"user_album_art", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public wireless_android_skyjam.ImageUnion user_album_art
    {
      get { return _user_album_art; }
      set { _user_album_art = value; }
    }
    private byte[] _enhanced_challenge_response = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"enhanced_challenge_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] enhanced_challenge_response
    {
      get { return _enhanced_challenge_response; }
      set { _enhanced_challenge_response = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UploadPlaylistRequest")]
  public partial class UploadPlaylistRequest : global::ProtoBuf.IExtensible
  {
    public UploadPlaylistRequest() {}
    
    private wireless_android_skyjam.UploadOperation _upload_operation;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"upload_operation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public wireless_android_skyjam.UploadOperation upload_operation
    {
      get { return _upload_operation; }
      set { _upload_operation = value; }
    }
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.Playlist> _playlist = new global::System.Collections.Generic.List<wireless_android_skyjam.Playlist>();
    [global::ProtoBuf.ProtoMember(2, Name=@"playlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.Playlist> playlist
    {
      get { return _playlist; }
    }
  
    private string _uploader_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"uploader_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uploader_id
    {
      get { return _uploader_id; }
      set { _uploader_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlaylistResponse")]
  public partial class PlaylistResponse : global::ProtoBuf.IExtensible
  {
    public PlaylistResponse() {}
    
    private wireless_android_skyjam.ResponseStatus _response_status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"response_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public wireless_android_skyjam.ResponseStatus response_status
    {
      get { return _response_status; }
      set { _response_status = value; }
    }
    private string _client_id = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"client_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string client_id
    {
      get { return _client_id; }
      set { _client_id = value; }
    }
    private string _server_id = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"server_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string server_id
    {
      get { return _server_id; }
      set { _server_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UploadPlaylistResponse")]
  public partial class UploadPlaylistResponse : global::ProtoBuf.IExtensible
  {
    public UploadPlaylistResponse() {}
    
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.PlaylistResponse> _playlist_response = new global::System.Collections.Generic.List<wireless_android_skyjam.PlaylistResponse>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playlist_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.PlaylistResponse> playlist_response
    {
      get { return _playlist_response; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UploadPlaylistEntryRequest")]
  public partial class UploadPlaylistEntryRequest : global::ProtoBuf.IExtensible
  {
    public UploadPlaylistEntryRequest() {}
    
    private wireless_android_skyjam.UploadOperation _upload_operation;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"upload_operation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public wireless_android_skyjam.UploadOperation upload_operation
    {
      get { return _upload_operation; }
      set { _upload_operation = value; }
    }
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.PlaylistEntry> _playlist_entry = new global::System.Collections.Generic.List<wireless_android_skyjam.PlaylistEntry>();
    [global::ProtoBuf.ProtoMember(2, Name=@"playlist_entry", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.PlaylistEntry> playlist_entry
    {
      get { return _playlist_entry; }
    }
  
    private string _uploader_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"uploader_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uploader_id
    {
      get { return _uploader_id; }
      set { _uploader_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlaylistEntryResponse")]
  public partial class PlaylistEntryResponse : global::ProtoBuf.IExtensible
  {
    public PlaylistEntryResponse() {}
    
    private wireless_android_skyjam.ResponseStatus _response_status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"response_status", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public wireless_android_skyjam.ResponseStatus response_status
    {
      get { return _response_status; }
      set { _response_status = value; }
    }
    private string _client_id = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"client_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string client_id
    {
      get { return _client_id; }
      set { _client_id = value; }
    }
    private string _server_id = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"server_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string server_id
    {
      get { return _server_id; }
      set { _server_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UploadPlaylistEntryResponse")]
  public partial class UploadPlaylistEntryResponse : global::ProtoBuf.IExtensible
  {
    public UploadPlaylistEntryResponse() {}
    
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.PlaylistEntryResponse> _playlist_entry_response = new global::System.Collections.Generic.List<wireless_android_skyjam.PlaylistEntryResponse>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playlist_entry_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.PlaylistEntryResponse> playlist_entry_response
    {
      get { return _playlist_entry_response; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UploadMetadataRequest")]
  public partial class UploadMetadataRequest : global::ProtoBuf.IExtensible
  {
    public UploadMetadataRequest() {}
    
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.Track> _track = new global::System.Collections.Generic.List<wireless_android_skyjam.Track>();
    [global::ProtoBuf.ProtoMember(1, Name=@"track", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.Track> track
    {
      get { return _track; }
    }
  
    private string _uploader_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uploader_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uploader_id
    {
      get { return _uploader_id; }
      set { _uploader_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateUploadStateRequest")]
  public partial class UpdateUploadStateRequest : global::ProtoBuf.IExtensible
  {
    public UpdateUploadStateRequest() {}
    
    private wireless_android_skyjam.UpdateUploadStateRequest.UploadState _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public wireless_android_skyjam.UpdateUploadStateRequest.UploadState state
    {
      get { return _state; }
      set { _state = value; }
    }
    private string _uploader_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uploader_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uploader_id
    {
      get { return _uploader_id; }
      set { _uploader_id = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"UploadState")]
    public enum UploadState
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"START", Value=1)]
      START = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PAUSED", Value=2)]
      PAUSED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STOPPED", Value=3)]
      STOPPED = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientStateRequest")]
  public partial class ClientStateRequest : global::ProtoBuf.IExtensible
  {
    public ClientStateRequest() {}
    
    private string _uploader_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uploader_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uploader_id
    {
      get { return _uploader_id; }
      set { _uploader_id = value; }
    }
    private long _get_purchased_tracks_since = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"get_purchased_tracks_since", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long get_purchased_tracks_since
    {
      get { return _get_purchased_tracks_since; }
      set { _get_purchased_tracks_since = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientStateResponse")]
  public partial class ClientStateResponse : global::ProtoBuf.IExtensible
  {
    public ClientStateResponse() {}
    
    private long _locker_track_limit = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"locker_track_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long locker_track_limit
    {
      get { return _locker_track_limit; }
      set { _locker_track_limit = value; }
    }
    private long _user_songs_in_locker = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_songs_in_locker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long user_songs_in_locker
    {
      get { return _user_songs_in_locker; }
      set { _user_songs_in_locker = value; }
    }
    private int _track_size_limit_in_mb = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"track_size_limit_in_mb", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int track_size_limit_in_mb
    {
      get { return _track_size_limit_in_mb; }
      set { _track_size_limit_in_mb = value; }
    }
    private long _user_purchased_tracks_since = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"user_purchased_tracks_since", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long user_purchased_tracks_since
    {
      get { return _user_purchased_tracks_since; }
      set { _user_purchased_tracks_since = value; }
    }
    private long _total_track_count = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"total_track_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long total_track_count
    {
      get { return _total_track_count; }
      set { _total_track_count = value; }
    }
    private wireless_android_skyjam.OverrideConfigValueCollection _override_config = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"override_config", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public wireless_android_skyjam.OverrideConfigValueCollection override_config
    {
      get { return _override_config; }
      set { _override_config = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UploadMetadataResponse")]
  public partial class UploadMetadataResponse : global::ProtoBuf.IExtensible
  {
    public UploadMetadataResponse() {}
    
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.SignedChallengeInfo> _signed_challenge_info = new global::System.Collections.Generic.List<wireless_android_skyjam.SignedChallengeInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"signed_challenge_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.SignedChallengeInfo> signed_challenge_info
    {
      get { return _signed_challenge_info; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _upload_id = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"upload_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> upload_id
    {
      get { return _upload_id; }
    }
  
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.TrackSampleResponse> _track_sample_response = new global::System.Collections.Generic.List<wireless_android_skyjam.TrackSampleResponse>();
    [global::ProtoBuf.ProtoMember(3, Name=@"track_sample_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.TrackSampleResponse> track_sample_response
    {
      get { return _track_sample_response; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TrackSampleResponse")]
  public partial class TrackSampleResponse : global::ProtoBuf.IExtensible
  {
    public TrackSampleResponse() {}
    
    private string _client_track_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"client_track_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string client_track_id
    {
      get { return _client_track_id; }
      set { _client_track_id = value; }
    }
    private wireless_android_skyjam.TrackSampleResponse.ResponseCode _response_code;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"response_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public wireless_android_skyjam.TrackSampleResponse.ResponseCode response_code
    {
      get { return _response_code; }
      set { _response_code = value; }
    }
    private string _server_track_id = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"server_track_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string server_track_id
    {
      get { return _server_track_id; }
      set { _server_track_id = value; }
    }
    private string _album_art_url = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"album_art_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string album_art_url
    {
      get { return _album_art_url; }
      set { _album_art_url = value; }
    }
    private bool _expect_match = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"expect_match", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool expect_match
    {
      get { return _expect_match; }
      set { _expect_match = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ResponseCode")]
    public enum ResponseCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MATCHED", Value=1)]
      MATCHED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPLOAD_REQUESTED", Value=2)]
      UPLOAD_REQUESTED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_SIGNATURE", Value=3)]
      INVALID_SIGNATURE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALREADY_EXISTS", Value=4)]
      ALREADY_EXISTS = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRANSIENT_ERROR", Value=5)]
      TRANSIENT_ERROR = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PERMANENT_ERROR", Value=6)]
      PERMANENT_ERROR = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRACK_COUNT_LIMIT_REACHED", Value=7)]
      TRACK_COUNT_LIMIT_REACHED = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REJECT_STORE_TRACK", Value=8)]
      REJECT_STORE_TRACK = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REJECT_STORE_TRACK_BY_LABEL", Value=9)]
      REJECT_STORE_TRACK_BY_LABEL = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REJECT_DRM_TRACK", Value=10)]
      REJECT_DRM_TRACK = 10
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UploadSampleRequest")]
  public partial class UploadSampleRequest : global::ProtoBuf.IExtensible
  {
    public UploadSampleRequest() {}
    
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.TrackSample> _track_sample = new global::System.Collections.Generic.List<wireless_android_skyjam.TrackSample>();
    [global::ProtoBuf.ProtoMember(1, Name=@"track_sample", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.TrackSample> track_sample
    {
      get { return _track_sample; }
    }
  
    private string _uploader_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uploader_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uploader_id
    {
      get { return _uploader_id; }
      set { _uploader_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UploadSampleResponse")]
  public partial class UploadSampleResponse : global::ProtoBuf.IExtensible
  {
    public UploadSampleResponse() {}
    
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.TrackSampleResponse> _track_sample_response = new global::System.Collections.Generic.List<wireless_android_skyjam.TrackSampleResponse>();
    [global::ProtoBuf.ProtoMember(1, Name=@"track_sample_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.TrackSampleResponse> track_sample_response
    {
      get { return _track_sample_response; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ImageUnion")]
  public partial class ImageUnion : global::ProtoBuf.IExtensible
  {
    public ImageUnion() {}
    
    private byte[] _user_album_art = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_album_art", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] user_album_art
    {
      get { return _user_album_art; }
      set { _user_album_art = value; }
    }
    private string _album_art_url = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"album_art_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string album_art_url
    {
      get { return _album_art_url; }
      set { _album_art_url = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UploadResponse")]
  public partial class UploadResponse : global::ProtoBuf.IExtensible
  {
    public UploadResponse() {}
    
    private wireless_android_skyjam.UploadResponse.ResponseType _response_type = wireless_android_skyjam.UploadResponse.ResponseType.METADATA_RESPONSE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"response_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.UploadResponse.ResponseType.METADATA_RESPONSE)]
    public wireless_android_skyjam.UploadResponse.ResponseType response_type
    {
      get { return _response_type; }
      set { _response_type = value; }
    }
    private wireless_android_skyjam.UploadMetadataResponse _metadata_response = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"metadata_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public wireless_android_skyjam.UploadMetadataResponse metadata_response
    {
      get { return _metadata_response; }
      set { _metadata_response = value; }
    }
    private wireless_android_skyjam.UploadPlaylistResponse _playlist_response = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playlist_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public wireless_android_skyjam.UploadPlaylistResponse playlist_response
    {
      get { return _playlist_response; }
      set { _playlist_response = value; }
    }
    private wireless_android_skyjam.UploadPlaylistEntryResponse _playlist_entry_response = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"playlist_entry_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public wireless_android_skyjam.UploadPlaylistEntryResponse playlist_entry_response
    {
      get { return _playlist_entry_response; }
      set { _playlist_entry_response = value; }
    }
    private wireless_android_skyjam.UploadSampleResponse _sample_response = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sample_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public wireless_android_skyjam.UploadSampleResponse sample_response
    {
      get { return _sample_response; }
      set { _sample_response = value; }
    }
    private wireless_android_skyjam.GetJobsResponse _getjobs_response = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"getjobs_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public wireless_android_skyjam.GetJobsResponse getjobs_response
    {
      get { return _getjobs_response; }
      set { _getjobs_response = value; }
    }
    private wireless_android_skyjam.ClientStateResponse _clientstate_response = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"clientstate_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public wireless_android_skyjam.ClientStateResponse clientstate_response
    {
      get { return _clientstate_response; }
      set { _clientstate_response = value; }
    }
    private wireless_android_skyjam.ClientPolicy _policy = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"policy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public wireless_android_skyjam.ClientPolicy policy
    {
      get { return _policy; }
      set { _policy = value; }
    }
    private wireless_android_skyjam.UploadResponse.AuthStatus _auth_status = wireless_android_skyjam.UploadResponse.AuthStatus.OK;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"auth_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.UploadResponse.AuthStatus.OK)]
    public wireless_android_skyjam.UploadResponse.AuthStatus auth_status
    {
      get { return _auth_status; }
      set { _auth_status = value; }
    }
    private bool _auth_error = default(bool);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"auth_error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool auth_error
    {
      get { return _auth_error; }
      set { _auth_error = value; }
    }
    private wireless_android_skyjam.UpAuthResponse _upauth_response = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"upauth_response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public wireless_android_skyjam.UpAuthResponse upauth_response
    {
      get { return _upauth_response; }
      set { _upauth_response = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ResponseType")]
    public enum ResponseType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"METADATA_RESPONSE", Value=1)]
      METADATA_RESPONSE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYLIST_RESPONSE", Value=2)]
      PLAYLIST_RESPONSE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYLIST_ENTRY_RESPONSE", Value=3)]
      PLAYLIST_ENTRY_RESPONSE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SAMPLE_RESPONSE", Value=4)]
      SAMPLE_RESPONSE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GETJOBS_RESPONSE", Value=5)]
      GETJOBS_RESPONSE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AUTH_RESPONSE", Value=6)]
      AUTH_RESPONSE = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT_STATE_RESPONSE", Value=7)]
      CLIENT_STATE_RESPONSE = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE_UPLOAD_STATE_RESPONSE", Value=8)]
      UPDATE_UPLOAD_STATE_RESPONSE = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DELETE_UPLOAD_REQUESTED_RESPONSE", Value=9)]
      DELETE_UPLOAD_REQUESTED_RESPONSE = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"AuthStatus")]
    public enum AuthStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OK", Value=8)]
      OK = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_LIMIT_REACHED", Value=9)]
      MAX_LIMIT_REACHED = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT_BOUND_TO_OTHER_ACCOUNT", Value=10)]
      CLIENT_BOUND_TO_OTHER_ACCOUNT = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT_NOT_AUTHORIZED", Value=11)]
      CLIENT_NOT_AUTHORIZED = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAX_PER_MACHINE_USERS_EXCEEDED", Value=12)]
      MAX_PER_MACHINE_USERS_EXCEEDED = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT_PLEASE_RETRY", Value=13)]
      CLIENT_PLEASE_RETRY = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOT_SUBSCRIBED", Value=14)]
      NOT_SUBSCRIBED = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INVALID_REQUEST", Value=15)]
      INVALID_REQUEST = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPGRADE_MUSIC_MANAGER", Value=16)]
      UPGRADE_MUSIC_MANAGER = 16
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TracksToUpload")]
  public partial class TracksToUpload : global::ProtoBuf.IExtensible
  {
    public TracksToUpload() {}
    
    private string _client_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"client_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string client_id
    {
      get { return _client_id; }
      set { _client_id = value; }
    }
    private string _server_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"server_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string server_id
    {
      get { return _server_id; }
      set { _server_id = value; }
    }
    private wireless_android_skyjam.TracksToUpload.TrackStatus _status;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public wireless_android_skyjam.TracksToUpload.TrackStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"TrackStatus")]
    public enum TrackStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE_REUPLOAD", Value=3)]
      FORCE_REUPLOAD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPLOAD_REQUESTED", Value=4)]
      UPLOAD_REQUESTED = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetJobsRequest")]
  public partial class GetJobsRequest : global::ProtoBuf.IExtensible
  {
    public GetJobsRequest() {}
    
    private string _uploader_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uploader_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uploader_id
    {
      get { return _uploader_id; }
      set { _uploader_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetJobsResponse")]
  public partial class GetJobsResponse : global::ProtoBuf.IExtensible
  {
    public GetJobsResponse() {}
    
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.TracksToUpload> _tracks_to_upload = new global::System.Collections.Generic.List<wireless_android_skyjam.TracksToUpload>();
    [global::ProtoBuf.ProtoMember(1, Name=@"tracks_to_upload", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.TracksToUpload> tracks_to_upload
    {
      get { return _tracks_to_upload; }
    }
  
    private bool _get_tracks_success;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"get_tracks_success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool get_tracks_success
    {
      get { return _get_tracks_success; }
      set { _get_tracks_success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpAuthRequest")]
  public partial class UpAuthRequest : global::ProtoBuf.IExtensible
  {
    public UpAuthRequest() {}
    
    private string _uploader_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uploader_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uploader_id
    {
      get { return _uploader_id; }
      set { _uploader_id = value; }
    }
    private string _friendly_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"friendly_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string friendly_name
    {
      get { return _friendly_name; }
      set { _friendly_name = value; }
    }
    private string _mac_identifier = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mac_identifier", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mac_identifier
    {
      get { return _mac_identifier; }
      set { _mac_identifier = value; }
    }
    private string _hash_identifier = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hash_identifier", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hash_identifier
    {
      get { return _hash_identifier; }
      set { _hash_identifier = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpAuthResponse")]
  public partial class UpAuthResponse : global::ProtoBuf.IExtensible
  {
    public UpAuthResponse() {}
    
    private string _uploader_id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uploader_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uploader_id
    {
      get { return _uploader_id; }
      set { _uploader_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeleteUploadRequestedRequest")]
  public partial class DeleteUploadRequestedRequest : global::ProtoBuf.IExtensible
  {
    public DeleteUploadRequestedRequest() {}
    
    private string _uploader_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uploader_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uploader_id
    {
      get { return _uploader_id; }
      set { _uploader_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ClientPolicy")]
  public partial class ClientPolicy : global::ProtoBuf.IExtensible
  {
    public ClientPolicy() {}
    
    private bool _pause_uploads = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pause_uploads", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool pause_uploads
    {
      get { return _pause_uploads; }
      set { _pause_uploads = value; }
    }
    private bool _abort = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"abort", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool abort
    {
      get { return _abort; }
      set { _abort = value; }
    }
    private int _retry_in_minutes = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"retry_in_minutes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int retry_in_minutes
    {
      get { return _retry_in_minutes; }
      set { _retry_in_minutes = value; }
    }
    private int _bandwidth_cap_kbps = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bandwidth_cap_kbps", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bandwidth_cap_kbps
    {
      get { return _bandwidth_cap_kbps; }
      set { _bandwidth_cap_kbps = value; }
    }
    private bool _pause_downloads = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"pause_downloads", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool pause_downloads
    {
      get { return _pause_downloads; }
      set { _pause_downloads = value; }
    }
    private int _download_bandwidth_cap_kbps = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"download_bandwidth_cap_kbps", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int download_bandwidth_cap_kbps
    {
      get { return _download_bandwidth_cap_kbps; }
      set { _download_bandwidth_cap_kbps = value; }
    }
    private bool _send_analytics = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"send_analytics", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool send_analytics
    {
      get { return _send_analytics; }
      set { _send_analytics = value; }
    }
    private string _analytics_url = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"analytics_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string analytics_url
    {
      get { return _analytics_url; }
      set { _analytics_url = value; }
    }
    private bool _enable_gapless = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"enable_gapless", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool enable_gapless
    {
      get { return _enable_gapless; }
      set { _enable_gapless = value; }
    }
    private bool _enable_m4p = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"enable_m4p", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool enable_m4p
    {
      get { return _enable_m4p; }
      set { _enable_m4p = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UploadMetadataInternalRequest")]
  public partial class UploadMetadataInternalRequest : global::ProtoBuf.IExtensible
  {
    public UploadMetadataInternalRequest() {}
    
    private ulong _gaiaid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gaiaid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong gaiaid
    {
      get { return _gaiaid; }
      set { _gaiaid = value; }
    }
    private wireless_android_skyjam.UploadMetadataRequest _request;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public wireless_android_skyjam.UploadMetadataRequest request
    {
      get { return _request; }
      set { _request = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OverrideConfigValue")]
  public partial class OverrideConfigValue : global::ProtoBuf.IExtensible
  {
    public OverrideConfigValue() {}
    
    private string _key = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private string _value = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private wireless_android_skyjam.OverrideConfigValue.OverridePriority _priority = wireless_android_skyjam.OverrideConfigValue.OverridePriority.DEFAULT_PRIORITY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"priority", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(wireless_android_skyjam.OverrideConfigValue.OverridePriority.DEFAULT_PRIORITY)]
    public wireless_android_skyjam.OverrideConfigValue.OverridePriority priority
    {
      get { return _priority; }
      set { _priority = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"OverridePriority")]
    public enum OverridePriority
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEFAULT_PRIORITY", Value=-1)]
      DEFAULT_PRIORITY = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOWEST_PRIORITY", Value=100)]
      LOWEST_PRIORITY = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOW_PRIORITY", Value=200)]
      LOW_PRIORITY = 200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MEDIUM_PRIORITY", Value=300)]
      MEDIUM_PRIORITY = 300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HIGH_PRIORITY", Value=400)]
      HIGH_PRIORITY = 400,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HIGHEST_PRIORITY", Value=500)]
      HIGHEST_PRIORITY = 500
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OverrideConfigValueCollection")]
  public partial class OverrideConfigValueCollection : global::ProtoBuf.IExtensible
  {
    public OverrideConfigValueCollection() {}
    
    private readonly global::System.Collections.Generic.List<wireless_android_skyjam.OverrideConfigValue> _value = new global::System.Collections.Generic.List<wireless_android_skyjam.OverrideConfigValue>();
    [global::ProtoBuf.ProtoMember(1, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<wireless_android_skyjam.OverrideConfigValue> value
    {
      get { return _value; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}